[pytest]

testpaths = tests
addopts = -v -rfs --html=reports/test_results.html
markers =
        create_repo: Create a repo for testing
        read_repo
        read_repo_sha
        update_repo
        remove_repo
        create_branch
        read_branch
        update_branch
        remove_branch
        fun_e2e_test
